### ISSUE TITLE
cross compilation with docker failed ( pathspec 'beta' did not match any file(s) known to git)

### ISSUE THREAD

**Issue by brenzi** [ethcore/parity-snappy#3]
I've tried the following on a ubuntu 16.04 x86_64 machine:
https://github.com/paritytech/parity-snappy/wiki/Docker-build-for-ARM-ARM64

```
> sudo docker build -t ethcore:parity-arm .

[...]

  stable installed - rustc 1.17.0 (56124baa9 2017-04-24)

 ---> 763202662ee7
Removing intermediate container f6eea35abfd3
Step 5 : ENV PATH /root/.cargo/bin:$PATH
 ---> Running in 4207e3c633dd
 ---> b49d3d1e0b5e
Removing intermediate container 4207e3c633dd
Step 6 : ENV RUST_TARGETS "arm-unknown-linux-gnueabihf"
 ---> Running in 05aa702df454
 ---> ba3f4d95e778
Removing intermediate container 05aa702df454
Step 7 : RUN rustup target add armv7-unknown-linux-gnueabihf
 ---> Running in aeb5e9a169c9
info: downloading component 'rust-std' for 'armv7-unknown-linux-gnueabihf'
info: installing component 'rust-std' for 'armv7-unknown-linux-gnueabihf'
 ---> 587cd2c0829e
Removing intermediate container aeb5e9a169c9
Step 8 : ENV RUST_BACKTRACE 1
 ---> Running in 8d993947412a
 ---> 4e950ddfca38
Removing intermediate container 8d993947412a
Step 9 : RUN rustc -vV &&  cargo -V
 ---> Running in 1b4a09c82676
rustc 1.17.0 (56124baa9 2017-04-24)
binary: rustc
commit-hash: 56124baa9e73f28c0709e59e74783cf234a978cf
commit-date: 2017-04-24
host: x86_64-unknown-linux-gnu
release: 1.17.0
LLVM version: 3.9
cargo 0.18.0 (fe7b0cdcf 2017-04-24)
 ---> 81d973decbda
Removing intermediate container 1b4a09c82676
Step 10 : RUN git clone https://github.com/ethcore/parity &&         cd parity &&         git checkout beta &&         git pull &&         mkdir -p .cargo &&         echo '[target.armv7-unknown-linux-gnueabihf]\n        linker = "arm-linux-gnueabihf-gcc"\n'        >>.cargo/config &&         cat .cargo/config &&         cargo build --target armv7-unknown-linux-gnueabihf --release --verbose &&         ls /build/parity/target/armv7-unknown-linux-gnueabihf/release/parity &&         /usr/bin/arm-linux-gnueabihf-strip /build/parity/target/armv7-unknown-linux-gnueabihf/release/parity
 ---> Running in 52852878a71f
Cloning into 'parity'...
error: pathspec 'beta' did not match any file(s) known to git.
The command '/bin/sh -c git clone https://github.com/ethcore/parity &&         cd parity &&         git checkout beta &&         git pull &&         mkdir -p .cargo &&         echo '[target.armv7-unknown-linux-gnueabihf]\n        linker = "arm-linux-gnueabihf-gcc"\n'        >>.cargo/config &&         cat .cargo/config &&         cargo build --target armv7-unknown-linux-gnueabihf --release --verbose &&         ls /build/parity/target/armv7-unknown-linux-gnueabihf/release/parity &&         /usr/bin/arm-linux-gnueabihf-strip /build/parity/target/armv7-unknown-linux-gnueabihf/release/parity' returned a non-zero code: 1
```

**Comment by brenzi** [comment]
looking at Dockerfile I see:
- the git repository path is obsolete. change to paritytech/parity
- the branch "beta" doesnt exist. I'll try to run it on master

**Comment by brenzi** [comment]
I've tried with master, but now it fails when compiling openssl-sys:
```
     Running `/build/parity/target/release/build/openssl-sys-881971d58354a91c/build-script-build`
error: failed to run custom build command for `openssl-sys v0.9.3`
process didn't exit successfully: `/build/parity/target/release/build/openssl-sys-881971d58354a91c/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-linux-gnu
    $TARGET = armv7-unknown-linux-gnueabihf
    openssl-sys = 0.9.3

', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.3/build.rs:142
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
   6: build_script_build::main
   7: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   9: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  10: __libc_start_main
  11: <unknown>

Build failed, waiting for other jobs to finish...
error: build failed

```
I've tried to specify OPENSSL_DIR, OPENSSL_LIB_DIR and OPENSSL_INCLUDE DIR, but it doesn't work

Here's my modified dockefile:
```
FROM ubuntu:14.04
WORKDIR /build
# install tools and dependencies
RUN apt-get -y update && \
        apt-get install -y --force-yes --no-install-recommends \
        curl git make g++ gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
        libc6-dev-armhf-cross wget file ca-certificates \
        binutils-arm-linux-gnueabihf libudev-dev libssl-dev openssl pkg-config \
        && \
    apt-get clean

# install rustup
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# rustup directory
ENV PATH /root/.cargo/bin:$PATH

ENV RUST_TARGETS="arm-unknown-linux-gnueabihf"

# multirust add arm--linux-gnuabhf toolchain
RUN rustup target add armv7-unknown-linux-gnueabihf

# show backtraces
ENV RUST_BACKTRACE 1

ENV OPENSSL_LIB_DIR /usr/lib/x86_64-linux-gnu/
ENV OPENSSL_INCLUDE_DIR /usr/include/openssl

# show tools
 RUN rustc -vV && \
 cargo -V

# build parity
RUN git clone https://github.com/paritytech/parity && \
        cd parity && \
        git checkout master && \
        git pull && \
        mkdir -p .cargo && \
        echo '[target.armv7-unknown-linux-gnueabihf]\n\
        linker = "arm-linux-gnueabihf-gcc"\n'\
        >>.cargo/config && \
        cat .cargo/config && \
        cargo build --target armv7-unknown-linux-gnueabihf --release --verbose && \
        ls /build/parity/target/armv7-unknown-linux-gnueabihf/release/parity && \
        /usr/bin/arm-linux-gnueabihf-strip /build/parity/target/armv7-unknown-linux-gnueabihf/release/parity

RUN file /build/parity/target/armv7-unknown-linux-gnueabihf/release/parity
```
I call the build with (included the env variables here as well as I wasn't sure where they're needed):
```
 OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu && OPENSSL_INCLUDE_DIR=/usr/include/openssl && sudo docker build -t e
```

**Comment by theMalapeno** [comment]
@brenzi did you manage to solve this issue by any chance? I'm stuck in the very same position unfortunately

**Comment by brenzi** [comment]
@theMalapeno no I'didn't. I'm just using the official binaries for ARM now

**Comment by hypnotortoise** [comment]
arm* targets are no longer served by Parity [starting from 2.0.7](https://github.com/paritytech/parity-ethereum/releases/tag/v2.0.7).

[Here's the current Dockerfile for cross-compiling the binary yourself (last tested with 2.3.0-beta)](https://github.com/paritytech/parity-ethereum/blob/beta/scripts/docker/ubuntu-aarch64/Dockerfile)
